# Generated by Django 5.1.1 on 2024-12-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
