# Generated by Django 5.1.1 on 2024-12-28 19:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
