# Generated by Django 5.1.1 on 2025-01-05 22:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
