# Generated by Django 5.1.1 on 2025-01-05 22:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models._post_image_upload_path
            ),
        ),
    ]
